import React, { useState, useEffect, useRef } from 'react'
import InteractiveDiagram from './InteractiveDiagram'
import RepositoryGraph from './RepositoryGraph'
import ChatSection from './ChatSection'

export default function Workspace({ tutorial, onBack }) {
  const [activeTab, setActiveTab] = useState('tutorial') // 'tutorial' | 'graph' | 'chat'
  const [selectedChapterKey, setSelectedChapterKey] = useState('overview')
  const [viewOpacity, setViewOpacity] = useState(1)
  const [activeTutorial, setActiveTutorial] = useState(tutorial)
  const contentPanelRef = useRef(null)

  // 1. Sync with prop changes
  useEffect(() => {
    setActiveTutorial(tutorial)
  }, [tutorial])

  // 2. Poll tutorial generation status from server in background
  useEffect(() => {
    if (activeTutorial && activeTutorial.status !== 'completed' && activeTutorial.status !== 'failed') {
      let isMounted = true
      
      const interval = setInterval(async () => {
        try {
          const response = await fetch(`/api/tutorials/${activeTutorial.id}`)
          const data = await response.json()
          
          if (isMounted && data && data.success) {
            setActiveTutorial(prev => ({
              ...prev,
              status: data.status,
              chat_ready: data.chat_ready,
              index_content: data.index_content,
              chapters: data.chapters,
              graph: data.graph
            }))
            
            if (data.status === 'completed' || data.status === 'failed') {
              clearInterval(interval)
            }
          }
        } catch (err) {
          console.error("Error polling tutorial status:", err)
        }
      }, 2000)

      return () => {
        isMounted = false
        clearInterval(interval)
      }
    }
  }, [activeTutorial?.id, activeTutorial?.status])

  const handleSelectChapter = (key) => {
    setViewOpacity(0)
    setTimeout(() => {
      setSelectedChapterKey(key)
      setViewOpacity(1)
      if (contentPanelRef.current) {
        contentPanelRef.current.scrollTop = 0
      }
    }, 250)
  }

  const handleOpenChapter = (chapterIdx) => {
    setActiveTab('tutorial')
    handleSelectChapter(chapterIdx)
  }

  const stripFooter = (content) => {
    if (!content) return ""
    return content.replace(/\n*---\s*\n*Generated by\s*\[AI Codebase[\s\S]*$/gi, '').trim()
  }

  const cleanTitle = (title) => {
    if (!title) return ""
    return title.replace(/^Chapter\s+\d+:\s*/i, '').trim()
  }

  const rawContent = selectedChapterKey === 'overview' 
    ? (activeTutorial.index_content || "") 
    : (activeTutorial.chapters && activeTutorial.chapters[selectedChapterKey] 
        ? activeTutorial.chapters[selectedChapterKey].content 
        : "")
  
  const sanitizedContent = stripFooter(rawContent)

  // Highlight and Mermaid hooks
  useEffect(() => {
    if (activeTab === 'tutorial' && activeTutorial.status === 'completed') {
      if (window.Prism && contentPanelRef.current) {
        window.Prism.highlightAllUnder(contentPanelRef.current)
      }
      if (window.mermaid && contentPanelRef.current) {
        const mermaidElements = contentPanelRef.current.querySelectorAll('.mermaid')
        if (mermaidElements.length > 0) {
          try {
            window.mermaid.run()
          } catch (err) {
            console.error("Mermaid generation error:", err)
          }
        }
      }
    }
  }, [selectedChapterKey, activeTutorial, activeTab])

  const renderContentSegments = () => {
    const parts = []
    let lastIndex = 0
    const regex = /```mermaid\s*\n(flowchart|graph)[\s\S]*?\n```/g
    let match
    
    while ((match = regex.exec(sanitizedContent)) !== null) {
      const textBefore = sanitizedContent.substring(lastIndex, match.index)
      if (textBefore.trim()) {
        parts.push({ type: 'markdown', content: textBefore })
      }
      
      const code = match[0].replace(/```mermaid\s*\n/, '').replace(/\n```/, '').trim()
      parts.push({ type: 'diagram', content: code })
      
      lastIndex = regex.lastIndex
    }
    
    const textAfter = sanitizedContent.substring(lastIndex)
    if (textAfter.trim()) {
      parts.push({ type: 'markdown', content: textAfter })
    }
    
    if (parts.length === 0) {
      parts.push({ type: 'markdown', content: sanitizedContent })
    }
    
    return parts.map((part, index) => {
      if (part.type === 'markdown') {
        const html = window.marked ? window.marked.parse(part.content) : part.content
        return (
          <div 
            key={index} 
            dangerouslySetInnerHTML={{ __html: html }} 
          />
        )
      } else {
        return (
          <InteractiveDiagram 
            key={index} 
            mermaidSrc={part.content} 
          />
        )
      }
    })
  }

  return (
    <div id="workspace" className="workspace" style={{ display: 'flex', flexDirection: 'column', height: '100%', gap: '1.2rem' }}>
      
      {/* Workspace Header Tab Bar */}
      <div className="workspace-header" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', width: '100%' }}>
        <button className="back-btn" onClick={onBack}>
          <svg viewBox="0 0 24 24" width="18" height="18">
            <line x1="19" y1="12" x2="5" y2="12"></line>
            <polyline points="12 19 5 12 12 5"></polyline>
          </svg>
          <span>Back to Home</span>
        </button>

        {/* View Selection Tabs */}
        <div style={{
          display: 'flex',
          background: 'rgba(255, 255, 255, 0.03)',
          border: '1px solid rgba(255, 255, 255, 0.05)',
          borderRadius: '30px',
          padding: '3px'
        }}>
          {[
            { 
              id: 'tutorial', 
              label: 'Tutorial', 
              icon: (
                <svg viewBox="0 0 24 24" width="14" height="14" fill="none" stroke="currentColor" strokeWidth="2" style={{ marginRight: '6.5px', display: 'inline-block', verticalAlign: 'middle' }}>
                  <path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20"></path>
                  <path d="M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2z"></path>
                </svg>
              )
            },
            { 
              id: 'graph', 
              label: 'Repository Graph', 
              icon: (
                <svg viewBox="0 0 24 24" width="14" height="14" fill="none" stroke="currentColor" strokeWidth="2" style={{ marginRight: '6.5px', display: 'inline-block', verticalAlign: 'middle' }}>
                  <circle cx="12" cy="12" r="3"></circle>
                  <circle cx="6" cy="6" r="3"></circle>
                  <circle cx="18" cy="6" r="3"></circle>
                  <circle cx="18" cy="18" r="3"></circle>
                  <line x1="12" y1="12" x2="6" y2="6"></line>
                  <line x1="12" y1="12" x2="18" y2="6"></line>
                  <line x1="12" y1="12" x2="18" y2="18"></line>
                </svg>
              )
            },
            { 
              id: 'chat', 
              label: activeTutorial.chat_ready ? 'Chat' : 'Chat (Locked)', 
              icon: (
                <div style={{ display: 'inline-flex', alignItems: 'center', gap: '3px', marginRight: '6.5px', verticalAlign: 'middle' }}>
                  <svg viewBox="0 0 24 24" width="14" height="14" fill="none" stroke="currentColor" strokeWidth="2">
                    <path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"></path>
                  </svg>
                  {!activeTutorial.chat_ready && (
                    <svg viewBox="0 0 24 24" width="11" height="11" fill="none" stroke="currentColor" strokeWidth="2.5">
                      <rect x="3" y="11" width="18" height="11" rx="2" ry="2"></rect>
                      <path d="M7 11V7a5 5 0 0 1 10 0v4"></path>
                    </svg>
                  )}
                </div>
              )
            }
          ].map(tab => (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id)}
              style={{
                display: 'flex',
                alignItems: 'center',
                background: activeTab === tab.id ? 'rgba(255, 255, 255, 0.08)' : 'none',
                border: 'none',
                outline: 'none',
                color: activeTab === tab.id ? '#FFFFFF' : 'var(--text-muted)',
                fontFamily: 'inherit',
                fontSize: '0.85rem',
                fontWeight: '600',
                padding: '0.5rem 1.2rem',
                borderRadius: '25px',
                cursor: 'pointer',
                transition: 'var(--transition-fast)'
              }}
            >
              {tab.icon}
              <span>{tab.label}</span>
            </button>
          ))}
        </div>
        <div style={{ width: '120px' }}></div> {/* Spacer to balance header */}
      </div>

      {/* Main Tab Views Switcher */}
      <div style={{ flexGrow: 1, position: 'relative' }}>
        
        {/* Tutorial Tab */}
        {activeTab === 'tutorial' && (
          <div style={{ display: 'grid', gridTemplateColumns: '290px 1fr', gap: '2rem', height: '100%' }}>
            
            {/* Left chapters navigation sidebar */}
            <aside className="sidebar glass-panel" style={{ height: 'calc(100vh - 10rem)', top: '0', position: 'relative' }}>
              <h2 className="sidebar-title">{activeTutorial.project_name}</h2>
              
              {activeTutorial.status === 'indexing' || activeTutorial.status === 'generating' ? (
                <div style={{ padding: '1rem', color: 'var(--text-muted)', fontSize: '0.85rem' }}>
                  Generating chapters...
                </div>
              ) : (
                <ul className="chapter-list">
                  <li 
                    className={`chapter-item ${selectedChapterKey === 'overview' ? 'active' : ''}`}
                    onClick={() => handleSelectChapter('overview')}
                    style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}
                  >
                    <span className="chapter-number" style={{ display: 'inline-flex', alignItems: 'center', justifyContent: 'center' }}>
                      <svg viewBox="0 0 24 24" width="14" height="14" fill="none" stroke="currentColor" strokeWidth="2.5" style={{ opacity: 0.85 }}>
                        <path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path>
                        <polyline points="9 22 9 12 15 12 15 22"></polyline>
                      </svg>
                    </span> Overview
                  </li>
                  {(activeTutorial.chapters || []).map((chapter, idx) => (
                    <li 
                      key={idx}
                      className={`chapter-item ${selectedChapterKey === idx ? 'active' : ''}`}
                      onClick={() => handleSelectChapter(idx)}
                    >
                      <span className="chapter-number">{String(idx + 1).padStart(2, '0')}</span> 
                      {cleanTitle(chapter.title)}
                    </li>
                  ))}
                </ul>
              )}
            </aside>

            {/* Right main viewer panel */}
            <main 
              ref={contentPanelRef} 
              className="viewer-panel glass-panel"
              style={{ opacity: viewOpacity, transition: 'opacity 0.25s ease-in-out', height: 'calc(100vh - 10rem)', margin: 0 }}
            >
              {activeTutorial.status !== 'completed' ? (
                <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', height: '100%', gap: '1.2rem', padding: '2rem' }}>
                  <div className="loader-visual">
                    <div className="glow-bar" style={{ animation: 'glow-slide 2.2s infinite ease-in-out' }}></div>
                  </div>
                  <h3 style={{ color: '#FFFFFF', fontWeight: '500', fontSize: '1.1rem' }}>
                    {activeTutorial.status === 'indexing' 
                      ? 'Indexing Codebase & Generating Vectors...' 
                      : 'PocketFlow Generating Tutorial Chapters...'}
                  </h3>
                  <p style={{ color: 'var(--text-muted)', fontSize: '0.86rem', textAlign: 'center', maxWidth: '420px', lineHeight: '1.5' }}>
                    We are analyzing definitions, building relationships, and writing explanations.
                    {activeTutorial.chat_ready && <strong style={{ color: 'var(--accent-purple)', display: 'block', marginTop: '0.5rem' }}>✓ RAG Chat is ready! Switch tabs to talk.</strong>}
                  </p>
                  
                  {/* Style for loading slide */}
                  <style>{`
                    @keyframes glow-slide {
                      0% { left: -100%; }
                      100% { left: 100%; }
                    }
                  `}</style>
                </div>
              ) : (
                <div className="markdown-body">
                  {renderContentSegments()}
                </div>
              )}
            </main>
          </div>
        )}

        {/* Repository Graph Tab */}
        {activeTab === 'graph' && (
          activeTutorial.graph ? (
            <RepositoryGraph 
              graphData={activeTutorial.graph} 
              onOpenChapter={handleOpenChapter} 
            />
          ) : (
            <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', height: '100%', gap: '1rem' }}>
              <div className="loader-visual"><div className="glow-bar" style={{ animation: 'glow-slide 2.2s infinite ease-in-out' }}></div></div>
              <h3 style={{ color: '#FFFFFF', fontWeight: '500' }}>Compiling Flow Visualizations...</h3>
            </div>
          )
        )}

        {/* Chat Tab */}
        {activeTab === 'chat' && (
          activeTutorial.chat_ready ? (
            <ChatSection tutorial={activeTutorial} />
          ) : (
            <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', height: '100%', gap: '1.2rem', padding: '2rem' }}>
              <svg viewBox="0 0 24 24" width="48" height="48" fill="none" stroke="currentColor" strokeWidth="2" style={{ animation: 'pulse-lock 1.5s infinite alternate', color: 'var(--accent-purple)', filter: 'drop-shadow(0 2px 10px rgba(139, 92, 246, 0.4))' }}>
                <rect x="3" y="11" width="18" height="11" rx="2" ry="2"></rect>
                <path d="M7 11V7a5 5 0 0 1 10 0v4"></path>
              </svg>
              <h3 style={{ color: '#FFFFFF', fontWeight: '500' }}>Vector Indexing in Progress</h3>
              <p style={{ color: 'var(--text-muted)', fontSize: '0.88rem', textAlign: 'center', maxWidth: '420px', lineHeight: '1.5' }}>
                The Chat assistant is currently locked while Tree-sitter builds semantic code chunks and stores them in MongoDB Atlas Vector Search.
              </p>
              <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginTop: '1rem' }}>
                <span className="dot" style={{ width: '8px', height: '8px', background: 'var(--accent-purple)', borderRadius: '50%', display: 'inline-block', animation: 'typing-dot 1.2s infinite' }}></span>
                <span style={{ color: 'var(--accent-purple)', fontSize: '0.85rem', fontWeight: '600' }}>Processing repository files...</span>
              </div>
              <style>{`
                @keyframes pulse-lock {
                  0% { transform: scale(1); }
                  100% { transform: scale(1.1); }
                }
                @keyframes typing-dot {
                  0%, 100% { transform: translateY(0); opacity: 0.3; }
                  50% { transform: translateY(-4px); opacity: 1; }
                }
              `}</style>
            </div>
          )
        )}
      </div>
    </div>
  )
}
