import React, { useState, useEffect, useRef } from 'react'
import InteractiveDiagram from './InteractiveDiagram'
import RepositoryGraph from './RepositoryGraph'
import ChatSection from './ChatSection'

export default function Workspace({ tutorial, onBack }) {
  const [activeTab, setActiveTab] = useState('tutorial') // 'tutorial' | 'graph' | 'chat'
  const [selectedChapterKey, setSelectedChapterKey] = useState('overview')
  const [viewOpacity, setViewOpacity] = useState(1)
  const contentPanelRef = useRef(null)

  const handleSelectChapter = (key) => {
    setViewOpacity(0)
    setTimeout(() => {
      setSelectedChapterKey(key)
      setViewOpacity(1)
      if (contentPanelRef.current) {
        contentPanelRef.current.scrollTop = 0
      }
    }, 250)
  }

  // Jump from Repository Graph node directly to a specific tutorial chapter
  const handleOpenChapter = (chapterIdx) => {
    setActiveTab('tutorial')
    handleSelectChapter(chapterIdx)
  }

  const stripFooter = (content) => {
    return content.replace(/\n*---\s*\n*Generated by\s*\[AI Codebase[\s\S]*$/gi, '').trim()
  }

  const cleanTitle = (title) => {
    return title.replace(/^Chapter\s+\d+:\s*/i, '').trim()
  }

  const rawContent = selectedChapterKey === 'overview' 
    ? tutorial.index_content 
    : tutorial.chapters[selectedChapterKey].content
  
  const sanitizedContent = stripFooter(rawContent)

  // Trigger highlight & mermaid updates
  useEffect(() => {
    if (activeTab === 'tutorial') {
      if (window.Prism && contentPanelRef.current) {
        window.Prism.highlightAllUnder(contentPanelRef.current)
      }
      if (window.mermaid && contentPanelRef.current) {
        const mermaidElements = contentPanelRef.current.querySelectorAll('.mermaid')
        if (mermaidElements.length > 0) {
          try {
            window.mermaid.run()
          } catch (err) {
            console.error("Mermaid generation error:", err)
          }
        }
      }
    }
  }, [selectedChapterKey, tutorial, activeTab])

  // Parse markdown segments and insert InteractiveDiagram components
  const renderContentSegments = () => {
    const parts = []
    let lastIndex = 0
    
    // Match flowchart/graph mermaid codeblocks
    const regex = /```mermaid\s*\n(flowchart|graph)[\s\S]*?\n```/g
    let match
    
    while ((match = regex.exec(sanitizedContent)) !== null) {
      const textBefore = sanitizedContent.substring(lastIndex, match.index)
      if (textBefore.trim()) {
        parts.push({ type: 'markdown', content: textBefore })
      }
      
      const code = match[0].replace(/```mermaid\s*\n/, '').replace(/\n```/, '').trim()
      parts.push({ type: 'diagram', content: code })
      
      lastIndex = regex.lastIndex
    }
    
    const textAfter = sanitizedContent.substring(lastIndex)
    if (textAfter.trim()) {
      parts.push({ type: 'markdown', content: textAfter })
    }
    
    if (parts.length === 0) {
      parts.push({ type: 'markdown', content: sanitizedContent })
    }
    
    return parts.map((part, index) => {
      if (part.type === 'markdown') {
        const html = window.marked ? window.marked.parse(part.content) : part.content
        return (
          <div 
            key={index} 
            dangerouslySetInnerHTML={{ __html: html }} 
          />
        )
      } else {
        return (
          <InteractiveDiagram 
            key={index} 
            mermaidSrc={part.content} 
          />
        )
      }
    })
  }

  return (
    <div id="workspace" className="workspace" style={{ display: 'flex', flexDirection: 'column', height: '100%', gap: '1.2rem' }}>
      
      {/* Workspace Header Tab Bar */}
      <div className="workspace-header" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', width: '100%' }}>
        <button className="back-btn" onClick={onBack}>
          <svg viewBox="0 0 24 24" width="18" height="18">
            <line x1="19" y1="12" x2="5" y2="12"></line>
            <polyline points="12 19 5 12 12 5"></polyline>
          </svg>
          <span>Back to Home</span>
        </button>

        {/* View Selection Tabs */}
        <div style={{
          display: 'flex',
          background: 'rgba(255, 255, 255, 0.03)',
          border: '1px solid rgba(255, 255, 255, 0.05)',
          borderRadius: '30px',
          padding: '3px'
        }}>
          {[
            { id: 'tutorial', label: '📖 Tutorial' },
            { id: 'graph', label: '🕸 Repository Graph' },
            { id: 'chat', label: '💬 Chat' }
          ].map(tab => (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id)}
              style={{
                background: activeTab === tab.id ? 'rgba(255, 255, 255, 0.08)' : 'none',
                border: 'none',
                outline: 'none',
                color: activeTab === tab.id ? '#FFFFFF' : 'var(--text-muted)',
                fontFamily: 'inherit',
                fontSize: '0.85rem',
                fontWeight: '600',
                padding: '0.5rem 1.2rem',
                borderRadius: '25px',
                cursor: 'pointer',
                transition: 'var(--transition-fast)'
              }}
            >
              {tab.label}
            </button>
          ))}
        </div>
        <div style={{ width: '120px' }}></div> {/* Spacer to balance header */}
      </div>

      {/* Main Tab Views Switcher */}
      <div style={{ flexGrow: 1, position: 'relative' }}>
        {activeTab === 'tutorial' && (
          <div style={{ display: 'grid', gridTemplateColumns: '290px 1fr', gap: '2rem', height: '100%' }}>
            
            {/* Left chapters navigation sidebar */}
            <aside className="sidebar glass-panel" style={{ height: 'calc(100vh - 10rem)', top: '0', position: 'relative' }}>
              <h2 className="sidebar-title">{tutorial.project_name}</h2>
              <ul className="chapter-list">
                <li 
                  className={`chapter-item ${selectedChapterKey === 'overview' ? 'active' : ''}`}
                  onClick={() => handleSelectChapter('overview')}
                >
                  <span className="chapter-number">🏠</span> Overview
                </li>
                {tutorial.chapters.map((chapter, idx) => (
                  <li 
                    key={idx}
                    className={`chapter-item ${selectedChapterKey === idx ? 'active' : ''}`}
                    onClick={() => handleSelectChapter(idx)}
                  >
                    <span className="chapter-number">{String(idx + 1).padStart(2, '0')}</span> 
                    {cleanTitle(chapter.title)}
                  </li>
                ))}
              </ul>
            </aside>

            {/* Right main viewer panel */}
            <main 
              ref={contentPanelRef} 
              className="viewer-panel glass-panel"
              style={{ opacity: viewOpacity, transition: 'opacity 0.25s ease-in-out', height: 'calc(100vh - 10rem)', margin: 0 }}
            >
              <div className="markdown-body">
                {renderContentSegments()}
              </div>
            </main>
          </div>
        )}

        {activeTab === 'graph' && (
          <RepositoryGraph 
            graphData={tutorial.graph} 
            onOpenChapter={handleOpenChapter} 
          />
        )}

        {activeTab === 'chat' && (
          <ChatSection tutorial={tutorial} />
        )}
      </div>
    </div>
  )
}
